fix: ast/message_id: use 0x1FFF_FFFF (1<<29 - 1) instead of 2^29 in test
Clippy now emits the warning:

error: using decimal literal for bitwise operation
  --> src/ast/message_id.rs:80:42
   |
80 |         let id = MessageId::Extended(2 ^ 29);
   |                                          ^^
   |
   = help: use binary (0b1_1101), hex (0x001d), or octal (0o35) notation for better readability
   = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.94.0/index.html#decimal_bitwise_operands
   = note: `-D clippy::decimal-bitwise-operands` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::decimal_bitwise_operands)]`

The test should rather test 0x1FFF_FFFF (1<<29 - 1) instead of 2 XOR 29 (31)